#!/bin/bash
source utils.sh

problem=$(env_get problem)
src="${problem}/main.cpp"
executable=./build/a.out
# input="${problem}/input"}
input="./build/input"
input_problem=$(env_get input_problem)

mkdir build -p

if [ -f ${executable} ]; then
  rm ${executable}
fi

# g++ ${src} -g -I. -std=c++26 -o ${executable}
g++ -x c++ -g -std=gnu++20 ${src} -o ${executable}
# -O2
# -static

if [ -e ${executable} ]; then
    # updates the input
    if [ "${input_problem}" != "${problem}" ] || [ ! -e ${input} ] || [ ! -s ${input} ]; then
      echo '' > ${input}
      "${EDITOR}" "${input}"
      env_set input_problem "${problem}"
    fi
    echo 'Program running...'
    cat ${input} | ${executable}
else
    echo 'Compilation failed. Retrying...'
    read -n 1 -r -s -p $'Press any key to continue...'
    ./solve ${problem}
fi
