#!/bin/bash
source utils.sh

cpp_start_point='222'

function usage() {
  echo 'Usage: solve.sh [--usage] [path/to/problem/] [--force]'
}

if [[ ${1-""} == "--usage" ]]; then
  usage
  exit 0
fi

template_dir="$(pwd)/templates"
problem="${1:-$(env_get problem)}"

mkdir ${problem} -p
# cd ${problem}
src="${problem}/main.cpp"

if [[ -e ${src} ]]; then
  cp ${src} ${src}.bak
  if [[ ${2-""} == "--force" ]]; then
    cp "${template_dir}/main.cpp" ${src}
  fi
else
  cp "${template_dir}/main.cpp" ${src}
fi
nvim ${src} +${cpp_start_point}
env_set problem ${problem}
