#!/bin/bash
source utils.sh

cpp_start_point='727'

function usage() {
  echo 'Usage: solve.sh [--usage] [path/to/problem/] [--force]'
}

if [[ ${1-""} == "--usage" ]]; then
  usage
  exit 0
fi

template_dir="templates"
problem="${1:-$(env_get problem)}"
src="${problem}/main.cpp"

mkdir ${problem} -p
if [[ -e ${src} ]]; then
  cp ${src} ${src}.bak
  if [[ ${2-""} == "--force" ]]; then
    cp "${template_dir}"/main.cpp ${src}
  fi
else
  cp "${template_dir}"/main.cpp ${src}
fi
nvim ${src} +${cpp_start_point}
env_set problem ${problem}
